// frontend/src/components/Sidebar.jsx
// Ruta: frontend/src/components/Sidebar.jsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import { LayoutDashboard, FileText, Users, Package, Settings, LogOut, ChevronRight } from 'lucide-react';
import ThemeToggle from './ThemeToggle.jsx';

const Sidebar = ({ onCloseMobile }) => {
  const { pathname } = useLocation();
  const { logout, user } = useAuth();

  const menuItems = [
    { path: '/', icon: LayoutDashboard, label: 'Resumen' },
    { path: '/cotizaciones', icon: FileText, label: 'Ventas y Doc.' },
    { path: '/clientes', icon: Users, label: 'Clientes' },
    { path: '/productos', icon: Package, label: 'Productos' },
    { path: '/configuracion', icon: Settings, label: 'Configuración' },
  ];

  const isActive = (path) => pathname === path || (path !== '/' && pathname.startsWith(path));

  return (
    <aside className="h-full flex flex-col bg-white dark:bg-surface-900 border-r border-slate-100 dark:border-surface-800 transition-colors duration-300">
      <div className="h-20 flex items-center px-6 border-b border-slate-100 dark:border-surface-800">
        <div className="flex items-center gap-3 font-black text-xl text-slate-900 dark:text-white tracking-tight">
          <div className="w-9 h-9 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-lg shadow-indigo-600/30 transform -rotate-3">
            F
          </div>
          <span>FacturaPro</span>
        </div>
      </div>

      <nav className="flex-1 overflow-y-auto py-8 px-4 space-y-2">
        <div className="px-3 mb-4 text-[10px] font-bold text-slate-400 dark:text-surface-500 uppercase tracking-[0.2em]">
          Menu Principal
        </div>
        
        {menuItems.map((item) => {
          const active = isActive(item.path);
          return (
            <Link
              key={item.path}
              to={item.path}
              onClick={onCloseMobile}
              className={`
                flex items-center justify-between px-4 py-3 rounded-xl text-sm font-semibold transition-all duration-300 group
                ${active 
                  ? 'bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 shadow-sm' 
                  : 'text-slate-500 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-surface-800 hover:text-slate-900 dark:hover:text-white'}
              `}
            >
              <div className="flex items-center gap-3">
                <item.icon size={18} strokeWidth={active ? 2.5 : 2} className={active ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-400 group-hover:text-indigo-500'} />
                <span>{item.label}</span>
              </div>
              {active && <ChevronRight size={16} className="text-indigo-600 dark:text-indigo-400" />}
            </Link>
          );
        })}
      </nav>

      <div className="p-5 border-t border-slate-100 dark:border-surface-800 bg-slate-50/50 dark:bg-surface-900/50">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500 flex items-center justify-center text-white font-bold shadow-md">
              {user?.nombre_completo?.charAt(0) || 'U'}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-slate-900 dark:text-white truncate">
                {user?.nombre_completo || 'Usuario'}
              </p>
              <p className="text-[10px] text-slate-500 dark:text-surface-400 truncate uppercase tracking-wider font-medium">
                {user?.rol || 'Administrador'}
              </p>
            </div>
          </div>
          <ThemeToggle />
        </div>
        
        <button
          onClick={logout}
          className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-bold text-red-600 dark:text-red-400 bg-white dark:bg-surface-800 border-2 border-red-50 dark:border-red-900/30 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-all"
        >
          <LogOut size={16} strokeWidth={2.5} />
          <span>Cerrar Sesión</span>
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;

// frontend/src/lib/components/Sidebar.svelte
<script>
  import { page } from '$app/stores';
  import { FileText, LayoutDashboard, Printer, Settings2 } from 'lucide-svelte';
  import { fade } from 'svelte/transition';

  export let mobileOpen = false;

  const menuItems = [
    { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
    { name: 'Cotizaciones', href: '/cotizaciones', icon: FileText },
    { name: 'Producción', href: '/produccion', icon: Printer },
    { name: 'Configuración', href: '/configuracion', icon: Settings2 }
  ];

  function closeMobile() {
    mobileOpen = false;
  }

  function isActive(href, pathname) {
    return pathname === href || pathname.startsWith(`${href}/`);
  }

  $: currentPath = $page.url.pathname;
</script>

{#if mobileOpen}
  <div
    class="fixed inset-0 z-40 bg-slate-950/60 backdrop-blur-sm md:hidden"
    on:click={closeMobile}
    on:keydown={(event) => event.key === 'Escape' && closeMobile()}
    role="button"
    tabindex="-1"
    transition:fade={{ duration: 150 }}
  ></div>
{/if}

<aside
  class="fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-slate-800 bg-slate-900 transition-transform duration-300 md:static md:z-auto
    {mobileOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}"
>
  <div class="border-b border-slate-800 px-6 py-7">
    <a href="/dashboard" class="flex items-center gap-4" on:click={closeMobile}>
      <div class="flex h-11 w-11 items-center justify-center rounded-2xl border border-emerald-500/30 bg-emerald-500/10">
        <Printer class="h-5 w-5 text-emerald-400" strokeWidth={1.9} />
      </div>

      <div class="min-w-0">
        <p class="text-[11px] font-semibold uppercase tracking-[0.28em] text-emerald-400/80">Midnight Forest</p>
        <h1 class="truncate text-lg font-semibold tracking-tight text-white">PrintFlow</h1>
      </div>
    </a>
  </div>

  <nav class="flex-1 px-4 py-6">
    <p class="px-4 text-[11px] font-semibold uppercase tracking-[0.28em] text-slate-500">Navegación</p>

    <div class="mt-4 space-y-1.5">
      {#each menuItems as item}
        <a
          href={item.href}
          on:click={closeMobile}
          class="group flex items-center gap-3 rounded-r-xl border-l-2 px-4 py-3 text-sm font-medium tracking-tight transition-all duration-200
            {isActive(item.href, currentPath)
              ? 'border-emerald-500 bg-slate-800/50 text-white'
              : 'border-transparent text-slate-300 hover:bg-slate-800/40 hover:text-white'}"
        >
          <svelte:component
            this={item.icon}
            class="h-5 w-5 shrink-0 {isActive(item.href, currentPath) ? 'text-emerald-400' : 'text-slate-400 group-hover:text-slate-200'}"
            strokeWidth={1.9}
          />
          <span>{item.name}</span>
        </a>
      {/each}
    </div>
  </nav>

  <div class="border-t border-slate-800 px-6 py-6">
    <div class="rounded-2xl border border-slate-800 bg-slate-800/40 p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)]">
      <p class="text-[11px] font-semibold uppercase tracking-[0.24em] text-slate-500">Base Operativa</p>
      <p class="mt-2 text-sm leading-6 text-slate-300">
        Acceso rápido al flujo comercial y de producción con una navegación limpia y persistente.
      </p>
    </div>
  </div>
</aside>
