// frontend/src/components/ui/Toast.jsx
import { createContext, useContext, useState, useCallback } from 'react';
import { CheckCircle, XCircle, X } from 'lucide-react';

const ToastContext = createContext(null);

export function ToastProvider({ children }) {
  const [toasts, setToasts] = useState([]);

  const push = useCallback((message, type = 'success') => {
    const id = Date.now();
    setToasts((prev) => [...prev, { id, message, type }]);
    setTimeout(() => setToasts((prev) => prev.filter((t) => t.id !== id)), 4000);
  }, []);

  const remove = useCallback((id) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  return (
    <ToastContext.Provider value={push}>
      {children}
      <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
        {toasts.map((t) => (
          <div
            key={t.id}
            className={`flex items-center gap-3 rounded-lg px-4 py-3 shadow-lg text-sm font-medium ${
              t.type === 'error'
                ? 'bg-red-600 text-white'
                : 'bg-gray-900 text-white'
            }`}
          >
            {t.type === 'error' ? (
              <XCircle className="h-4 w-4 shrink-0" />
            ) : (
              <CheckCircle className="h-4 w-4 shrink-0" />
            )}
            <span className="flex-1">{t.message}</span>
            <button onClick={() => remove(t.id)} className="ml-2 opacity-70 hover:opacity-100">
              <X className="h-3.5 w-3.5" />
            </button>
          </div>
        ))}
      </div>
    </ToastContext.Provider>
  );
}

export function useToast() {
  return useContext(ToastContext);
}

// frontend/src/lib/components/Toast.svelte
<script>
  import { writable } from 'svelte/store';
  import { fly, fade } from 'svelte/transition';
  import { CheckCircle, AlertCircle, Info, AlertTriangle, X } from 'lucide-svelte';

  // Toast store
  export const toasts = writable([]);

  let toastList = [];
  toasts.subscribe(v => toastList = v);

  export function addToast(message, type = 'success', duration = 4000) {
    const id = Date.now();
    toasts.update(t => [...t, { id, message, type }]);
    if (duration > 0) {
      setTimeout(() => removeToast(id), duration);
    }
  }

  function removeToast(id) {
    toasts.update(t => t.filter(toast => toast.id !== id));
  }

  const icons = {
    success: CheckCircle,
    error: AlertCircle,
    warning: AlertTriangle,
    info: Info
  };

  const styles = {
    success: 'bg-success/10 border-success/20 text-success',
    error: 'bg-error/10 border-error/20 text-error',
    warning: 'bg-warning/10 border-warning/20 text-warning',
    info: 'bg-info/10 border-info/20 text-info'
  };
</script>

<div class="fixed top-4 right-4 z-[100] flex flex-col gap-3 max-w-sm w-full pointer-events-none">
  {#each toastList as toast (toast.id)}
    <div 
      class="pointer-events-auto flex items-start gap-3 p-4 rounded-2xl border backdrop-blur-xl shadow-lg {styles[toast.type] || styles.info}"
      in:fly={{ x: 100, duration: 300 }}
      out:fade={{ duration: 200 }}
    >
      <svelte:component this={icons[toast.type] || icons.info} size={20} class="shrink-0 mt-0.5" />
      <p class="text-sm font-semibold flex-1">{toast.message}</p>
      <button 
        on:click={() => removeToast(toast.id)}
        class="shrink-0 p-0.5 rounded-lg hover:bg-black/5 transition-colors"
      >
        <X size={14} />
      </button>
    </div>
  {/each}
</div>
